        name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter the model name, like "varoriya/xtts-v2-thai"'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download model from Hugging Face
        run: |
          mkdir -p models/khanomtan-tts-v1.0
          wget -O models/khanomtan-tts-v1.0/config.json https://huggingface.co/wannaphong/khanomtan-tts-v1.0/resolve/main/config.json
          wget -O models/khanomtan-tts-v1.0/pytorch_model.bin https://huggingface.co/wannaphong/khanomtan-tts-v1.0/resolve/main/pytorch_model.bin
          wget -O models/khanomtan-tts-v1.0/preprocessor_config.json https://huggingface.co/wannaphong/khanomtan-tts-v1.0/resolve/main/preprocessor_config.json

      - name: Push to Replicate
        run: cog push r8.im/varoriya/xtts-v2-thai


