name: Deploy to Replicate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ดึงโค้ดจาก Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # ติดตั้ง Python และ Cog
      - name: Setup Python and Install Cog
        run: |
          python3 -m pip install --upgrade pip
          pip install cog

      # ตรวจสอบว่า Cog ถูกติดตั้งสำเร็จ
      - name: Verify Cog installation
        run: cog --version

      # Deploy โมเดลไปยัง Replicate
      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: cog push
